<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modelo" nsURI="http://www.example.org/modelo" nsPrefix="modelo">
  <eClassifiers xsi:type="ecore:EClass" name="SLA">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slaparameters" eType="#//SLAParameters"
        eOpposite="#//SLAParameters/sla"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="integrationsla" eType="#//IntegrationSLA"
        eOpposite="#//IntegrationSLA/sla"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="party" eType="#//Party"
        eOpposite="#//Party/sla"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="obligation" eType="#//Obligation"
        eOpposite="#//Obligation/sla"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserSLA" eSuperTypes="#//SLA"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceSLA" eSuperTypes="#//SLA"/>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//Party">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cloud" eType="#//Cloud"
        eOpposite="#//Cloud/user"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cloud" eSuperTypes="#//Party">
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User" eOpposite="#//User/cloud"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" eType="#//Service"
        eOpposite="#//Service/cloud"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//Party">
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" eType="#//Query"
        eOpposite="#//Query/service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servicecomposition" eType="#//ServiceComposition"
        eOpposite="#//ServiceComposition/service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cloud" eType="#//Cloud"
        eOpposite="#//Cloud/service"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Party">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sla" eType="#//SLA" eOpposite="#//SLA/party"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Query">
    <eStructuralFeatures xsi:type="ecore:EReference" name="concepts" eType="#//Concepts"
        eOpposite="#//Concepts/query"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" eType="#//Query"
        eOpposite="#//Query/queryeOpposite"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queryeOpposite" eType="#//Query"
        eOpposite="#//Query/query"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" eType="#//Service"
        eOpposite="#//Service/query"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servicecomposition" eType="#//ServiceComposition"
        eOpposite="#//ServiceComposition/query"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceComposition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" eType="#//Service"
        eOpposite="#//Service/servicecomposition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" eType="#//Query"
        eOpposite="#//Query/servicecomposition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concepts">
    <eStructuralFeatures xsi:type="ecore:EReference" name="integrationsla" eType="#//IntegrationSLA"
        eOpposite="#//IntegrationSLA/concepts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" eType="#//Query"
        eOpposite="#//Query/concepts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegrationSLA">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sla" eType="#//SLA" eOpposite="#//SLA/integrationsla"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concepts" eType="#//Concepts"
        eOpposite="#//Concepts/integrationsla"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="negotiationrules" eType="#//NegotiationRules"
        eOpposite="#//NegotiationRules/integrationsla"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NegotiationRules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="integrationsla" eType="#//IntegrationSLA"
        eOpposite="#//IntegrationSLA/negotiationrules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guaranty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slaparameters" eType="#//SLAParameters"
        eOpposite="#//SLAParameters/guaranty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guaranty" eType="#//Guaranty"
        eOpposite="#//Guaranty/guarantyeOpposite"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guarantyeOpposite" eType="#//Guaranty"
        eOpposite="#//Guaranty/guaranty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Obligation" eSuperTypes="#//Guaranty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sla" eType="#//SLA" eOpposite="#//SLA/obligation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SLAParameters">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sla" eType="#//SLA" eOpposite="#//SLA/slaparameters"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guaranty" eType="#//Guaranty"
        eOpposite="#//Guaranty/slaparameters"/>
  </eClassifiers>
</ecore:EPackage>
